// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2Wr0RQdjpWfkeF_Yv4vXggAbm6I7JxPk',
    appId: '1:826880639726:web:962bc3e206a29a4f5aa9ff',
    messagingSenderId: '826880639726',
    projectId: 'voyager-sanctuary',
    authDomain: 'voyager-sanctuary.firebaseapp.com',
    storageBucket: 'voyager-sanctuary.firebasestorage.app',
    measurementId: 'G-PYYMJ5P096',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDshv_QlRzYPSgqoFAsbb2pUQ83nn16Cok',
    appId: '1:826880639726:android:095964bfe47ee3945aa9ff',
    messagingSenderId: '826880639726',
    projectId: 'voyager-sanctuary',
    storageBucket: 'voyager-sanctuary.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBnF_4DXT14z1RMpl_Z7e71zwvvsrOjWQ',
    appId: '1:826880639726:ios:9078bc56097568535aa9ff',
    messagingSenderId: '826880639726',
    projectId: 'voyager-sanctuary',
    storageBucket: 'voyager-sanctuary.firebasestorage.app',
    iosBundleId: 'com.voyagersanctuary.voyagerSanctuary',
  );
}
